from dataclasses import dataclass
from decimal import Decimal

import pandas as pd

from .models import Candle, Fill, Side
from .portfolio import Portfolio
from .strategies import GridStrategy


@dataclass
class BacktestConfig:
    slippage_bps: float = 1.0
    fee_per_order: Decimal = Decimal("20")


class BacktestEngine:
    def __init__(
        self,
        strategy: GridStrategy,
        config: BacktestConfig | None = None,
    ):
        self.strategy = strategy
        self.config = config or BacktestConfig()

    def _execution_price(self, price: float, side: Side) -> Decimal:
        slippage = Decimal(str(self.config.slippage_bps / 10000))
        execution = Decimal(str(price))

        if side == Side.BUY:
            return execution * (Decimal("1") + slippage)

        return execution * (Decimal("1") - slippage)

    def run(self, data: pd.DataFrame) -> Portfolio:
        required = {"open", "high", "low", "close", "volume"}
        missing = required - set(data.columns)

        if missing:
            raise ValueError(f"Missing columns: {sorted(missing)}")

        if "atr" not in data.columns:
            raise ValueError("Backtest data must contain a precomputed ATR column")

        if len(data) < 2:
            return Portfolio()

        portfolio = Portfolio()
        reference_price = float(data.iloc[0]["close"])

        pending_signal = None

        for i in range(1, len(data)):
            row = data.iloc[i]
            timestamp = data.index[i]

            candle = Candle(
                timestamp=timestamp,
                open=float(row["open"]),
                high=float(row["high"]),
                low=float(row["low"]),
                close=float(row["close"]),
                volume=float(row["volume"]),
            )

            # Execute the signal generated by the PREVIOUS bar.
            if pending_signal is not None:
                fill_price = self._execution_price(
                    candle.open,
                    pending_signal.side,
                )

                fill = Fill(
                    order_id=f"BT-{i}",
                    timestamp=timestamp,
                    side=pending_signal.side,
                    quantity=pending_signal.quantity,
                    price=fill_price,
                    fees=self.config.fee_per_order,
                )

                portfolio.apply_fill(fill)

            # Generate today's signal only AFTER execution of yesterday's signal.
            pending_signal = self.strategy.generate_signal(
                candle=candle,
                atr_value=float(row["atr"]),
                reference_price=reference_price,
                current_position=portfolio.position.quantity,
            )

        return portfolio